version: "3.8"
services:
  wg-easy:
    image: wg-easy
    command: npm run serve
    volumes:
      - ./frontend/:/app/frontend/
      - ./backend/:/app/backend/
    environment:
      # - PASSWORD=p
      - WG_HOST=192.168.1.233
