services:
  wg-easy:
    build:
      dockerfile: ./Dockerfile-dev
    command: pnpm run dev
    volumes:
      - ./src/:/app/
      # Breaks type completion otherwise
      - temp:/app/.nuxt
      # - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # - PASSWORD=p
      - WG_HOST=192.168.1.233

volumes:
  temp:
    driver: local
